### ISSUE TITLE
Would you mind adding a .npmignore

### ISSUE THREAD

**Issue by joh-klein** [szmarczak/resolve-alpn#2]
Hi, 
thanks for the tool (since it is a dependency of a dependency of got - rather, thanks for that :) ). I am pruning my dependencies (AWS Lambda upload) and just saw, that the .github folder and the test.js are part of the package – if that is on purpose, I am sorry and please close this issue, if not, maybe you can find the time and add a .npmignore?

Thx!

**Comment by szmarczak** [comment]
We just need to specify `files` in `package.json`. Good catch!

**Comment by szmarczak** [comment]
Done
